export enum InteractionKey {
    STARTX = "STARTX",
    STARTY = "STARTY",
    ENDX = "ENDX",
    ENDY = "ENDY",
  
    ABSOLUTE = "ABSOLUTE",
    ALPHA = "ALPHA",
    BETA = "BETA",
    GAMMA = "GAMMA",
  
    ACCELERATIONX = "ACCELERATIONX",
    ACCELERATIONY = "ACCELERATIONY",
    ACCELERATIONZ = "ACCELERATIONY",
    ACCELERATIONGRAVITYX = "ACCELERATIONGRAVITYX",
    ACCELERATIONGRAVITYY = "ACCELERATIONGRAVITYY",
    ACCELERATIONGRAVITYZ = "ACCELERATIONGRAVITYY",
    INTERVAL = "INTERVAL",
  
    PROGRESSPERCENT = "PROGRESSPERCENT",
    SPEED = "SPEED",
    SOUND = "SOUND",
    
    SELECTED = "SELECTED",
    OPTIONS = "OPTIONS",
    MULTIPLE = "MULTIPLE",
    TEXT = "TEXT",
  }